version: '3'
services:
  web:
      build:
          context: ./docker
          dockerfile: web.dockerfile
      container_name: laravel-sanctum-demo
      working_dir: /var/www
      volumes:
          - ./:/var/www
          - ./public/storage:/var/www/public/storage
      ports:
          - 80:80
      links:
          - app
      env_file:
          - .env
  app:
      build:
          context: ./docker
          dockerfile: app.dockerfile
      working_dir: /var/www
      volumes:
          - ./:/var/www
          - ./public/storage:/var/www/public/storage
      links:
          - database
      environment:
          - "DB_PORT=3306"
          - "DB_HOST=database"
  database:
    image: mysql:latest
    volumes:
          - "db-data:/var/lib/mysql/"
    environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laravel-sanctum-demo
        - MYSQL_user=root
        - MYSQL_PASSWORD=secret
    ports:
        - 33061:3306
volumes:
  db-data:
